In [1]:
import numpy as np

In [2]:
D1 = np.array([
    [1, 0, 2, 0],
    [0, 2, 4, -2],
    [-1, 0, -3, 1],
    [0, -1, -1, 0]
])

D2 = np.array([
    [1, -1, 0, 2],
    [-1, 0, 1, -1],
    [0, -2, 0, 1],
    [3, 0, -1, 0]
])

In [6]:
print(np.linalg.det(D1))
print(np.linalg.det(D2))

0.0
-8.000000000000002


In [7]:
print(np.linalg.matrix_rank(D1))
print(np.linalg.matrix_rank(D2))

3
4


In [14]:
theta = np.array([[-1],[0],[1],[2]])

In [ ]:
np.dot(D1, np.transpose(theta))


ValueError: shapes (4,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [21]:
A = np.array([
    [1, 1, 0, 0, 0],
    [1, 0, 1, 1, 0],
    [0, 0, 1, 1, 1],
    [0, 1, 1, 1, 1]
])
np.dot(A, A.T)

array([[2, 1, 0, 1],
       [1, 3, 2, 2],
       [0, 2, 3, 3],
       [1, 2, 3, 4]])

In [22]:
np.dot(A.T, A)

array([[2, 1, 1, 1, 0],
       [1, 2, 1, 1, 1],
       [1, 1, 3, 3, 2],
       [1, 1, 3, 3, 2],
       [0, 1, 2, 2, 2]])

In [25]:
import numpy as np
np.random.seed(42)

matrices = [np.random.randint(-10, 11, size=(3,3)) for _ in range(3)]

for i, M in enumerate(matrices, 1):
    print(f"Matrix {i}:\n{M}\n")
    try:
        M_inv = np.linalg.inv(M)
        print(f"Inverse of Matrix {i}:\n{M_inv}\n")
        product = np.dot(M, M_inv)
        product = np.round(product, decimals = 10)
        print(f"Product: {product}\n")
    except np.linalg.LinAlgError:
        print(f"Matrix {i} is not invertible.\n")


Matrix 1:
[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]

Inverse of Matrix 1:
[[ 0.90909091 -0.36363636 -1.15909091]
 [ 0.45454545 -0.18181818 -0.45454545]
 [ 0.13636364  0.04545455 -0.13636364]]

Product: [[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

Matrix 2:
[[ 0 10 -7]
 [-3 -8 10]
 [-9  1 -5]]

Inverse of Matrix 2:
[[-0.05714286 -0.08190476 -0.08380952]
 [ 0.2         0.12       -0.04      ]
 [ 0.14285714  0.17142857 -0.05714286]]

Product: [[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

Matrix 3:
[[ -9  10 -10]
 [  1   1   6]
 [ -1   5   4]]

Inverse of Matrix 3:
[[-0.35135135 -1.21621622  0.94594595]
 [-0.13513514 -0.62162162  0.59459459]
 [ 0.08108108  0.47297297 -0.25675676]]

Product: [[ 1. -0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]



In [28]:
import pandas as pd

df = pd.read_csv("kc_house_data.csv")

df = df.drop(columns=['id', 'date', 'zipcode'])

numeric_cols = df.select_dtypes(include='number')


In [29]:
mean_values = numeric_cols.mean()
min_values = numeric_cols.min()
max_values = numeric_cols.max()
variance_values = numeric_cols.var()

stats = pd.DataFrame({
    'Mean': mean_values,
    'Min': min_values,
    'Max': max_values,
    'Variance': variance_values
})

print("Feature statistics:\n", stats)

lowest_mean_feature = stats['Mean'].idxmin()
highest_mean_feature = stats['Mean'].idxmax()

print("\nLowest average feature:", lowest_mean_feature, stats.loc[lowest_mean_feature, 'Mean'])
print("Highest average feature:", highest_mean_feature, stats.loc[highest_mean_feature, 'Mean'])

lowest_var_feature = stats['Variance'].idxmin()
highest_var_feature = stats['Variance'].idxmax()

print("\nLowest variance feature:", lowest_var_feature, stats.loc[lowest_var_feature, 'Variance'])
print("Highest variance feature:", highest_var_feature, stats.loc[highest_var_feature, 'Variance'])


Feature statistics:
                         Mean         Min           Max      Variance
price          540088.141767  75000.0000  7.700000e+06  1.347824e+11
bedrooms            3.370842      0.0000  3.300000e+01  8.650150e-01
bathrooms           2.114757      0.0000  8.000000e+00  5.931513e-01
sqft_living      2079.899736    290.0000  1.354000e+04  8.435337e+05
sqft_lot        15106.967566    520.0000  1.651359e+06  1.715659e+09
floors              1.494309      1.0000  3.500000e+00  2.915880e-01
waterfront          0.007542      0.0000  1.000000e+00  7.485226e-03
view                0.234303      0.0000  4.000000e+00  5.872426e-01
condition           3.409430      1.0000  5.000000e+00  4.234665e-01
grade               7.656873      1.0000  1.300000e+01  1.381703e+00
sqft_above       1788.390691    290.0000  9.410000e+03  6.857347e+05
sqft_basement     291.509045      0.0000  4.820000e+03  1.958727e+05
yr_built         1971.005136   1900.0000  2.015000e+03  8.627973e+02
yr_renovated 

In [30]:
correlation = numeric_cols.corr()['price'].sort_values(ascending=False)

print("\nCorrelation with price:\n", correlation)

positive_corr = correlation[correlation > 0].index.tolist()
print("\nFeatures positively correlated with price:", positive_corr)

highest_corr_feature = correlation.idxmax()
print("Feature with highest positive correlation:", highest_corr_feature, correlation[highest_corr_feature])

negative_corr = correlation[correlation < 0]
print("\nFeatures negatively correlated with price:\n", negative_corr)



Correlation with price:
 price            1.000000
sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
yr_built         0.054012
condition        0.036362
long             0.021626
Name: price, dtype: float64

Features positively correlated with price: ['price', 'sqft_living', 'grade', 'sqft_above', 'sqft_living15', 'bathrooms', 'view', 'sqft_basement', 'bedrooms', 'lat', 'waterfront', 'floors', 'yr_renovated', 'sqft_lot', 'sqft_lot15', 'yr_built', 'condition', 'long']
Feature with highest positive correlation: price 1.0

Features negatively correlated with price:
 Series([], Name: price, dtype: float64)
